options:
  cache-config: true
rules:
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero:
    - 1
    - include: true
  no-color-literals: 0
  no-empty-rulesets: 0
  no-color-keywords: 0
  no-css-comments: 0
  placeholder-in-extend: 1
  no-misspelled-properties:
    - 1
    - 'extra-properties':
      - 'overflow-scrolling'
      - 'backdrop-filter'
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
  no-transition-all: 1
  no-vendor-prefixes:
    - 1
    - ignore-non-standard: true
  no-warn: 0

  # These could be enabled when a standard is set
  class-name-format: 0
  placeholder-name-format: 0
  id-name-format: 0
  property-sort-order: 0
