field: 90150e6a-b714-4f66-90ea-1680e9f6dbf2
fieldLayouts:
  53f8afd9-d2d3-46f7-ad6f-5c6810cd9523:
    tabs:
      -
        fields:
          ec0606ae-39c4-4061-bc84-8b28fa99790f:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  ec0606ae-39c4-4061-bc84-8b28fa99790f:
    contentColumnType: string
    fieldGroup: null
    handle: sliderImages
    instructions: ''
    name: 'Slider Images'
    searchable: '1'
    settings:
      columns: null
      contentTable: '{{%stc_4_sliderimages}}'
      fieldLayout: row
      localizeBlocks: false
      maxRows: ''
      minRows: ''
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: slider
name: Slider
sortOrder: 1
