fieldLayouts:
  c60e0109-776e-4b13-9e13-8bab75f24d15:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 1403e203-74fb-432b-a599-edfc307959f7
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a17859ac-a871-4aa9-b47b-2781a31027b7
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 74bf6db7-caab-4f5f-ad43-1bd3b9fd2c82
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: d1b564f6-1b00-466a-a82f-1cc6f532f1d2
sortOrder: 1
titleFormat: '{section.name|raw}'
