contentColumnType: text
fieldGroup: 7b578773-6463-427d-8aed-f17a94a6394e
handle: body
instructions: ''
name: Body
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: '1'
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
