dateModified: 1699782287
email:
  fromEmail: colette@builtbybuffalo.com
  fromName: 'Gin Rimmington'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0ecbf7a1-6479-4d8b-80a4-997f8427fcac: SEO # SEO
    8725841d-29a6-420b-b616-3266c04c7b36: 'Social Media' # Social Media
plugins:
  assetrev:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.0.0
    settings: null
  super-table:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.2.1
    settings: null
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Gin Rimmington Jones'
  schemaVersion: 3.8.0.1
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
