fieldLayouts:
  8ecc666b-99af-428c-9e2d-c5f0e815f08d:
    tabs:
      -
        fields:
          c979b298-78f7-44d4-b65a-a00194f43707:
            required: false
            sortOrder: 1
        name: 'Social Media'
        sortOrder: 1
handle: socialMedia
name: 'Social Media'
sortOrder: 2
